version: '3.9'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_PORT: 5432
    ports:
      - "5432:5432"
    container_name: postgres

  php7.4:
    build:
      context: ./
      dockerfile: docker/app/Dockerfile
    volumes:
      - "./:/app"
    working_dir: "/app"
    ports:
      - "9000:9000"
    depends_on:
      - postgres
    container_name: php7.4

  nginx:
    build:
      context: ./
      dockerfile: docker/nginx/Dockerfile
    working_dir: "/app"
    volumes:
      - "./:/app"
    depends_on:
      - "php7.4"
      - "postgres"
    container_name: nginx
    ports:
      - "80:80"